version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      # - 80:80
      - 443:443
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt/live/

volumes:
  {}